// <auto-generated />
namespace Estacionamento_banco_de_dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Registro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registro));
        
        string IMigrationMetadata.Id
        {
            get { return "202008280113170_Registro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
